[workspace]
resolver = "2"
members = [
    "crates/bsl-number",
    "crates/bsl-syntax",
    "crates/bsl-sema",
    "crates/bsl-rt",
    "crates/bsl-binbuf",
    "crates/bsl-regexp",
    "crates/bsl-textdoc",
    "crates/bsl-json",
    "crates/bsl-spreadsheet",
    "crates/bsl-stream",
    "crates/bsl-http",
    "crates/bsl-crypto",
    "crates/bsl-pdf",
    "crates/bsl-xml",
    "crates/bsl-zip",
    "crates/bsl-format",
    "crates/bsl-bytecode",
    "crates/bsl-compiler",
    "crates/bsl-vm",
    "crates/bsl-cli",
    "crates/open-bsl",
    "crates/open-bsl-consumer",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-or-later"

[profile.profiling]
inherits = "release"
debug = true
