[workspace]
resolver = "2"
members = [
    "crates/bsl-number",
    "crates/bsl-syntax",
    "crates/bsl-sema",
    "crates/bsl-rt",
    "crates/bsl-binbuf",
    "crates/bsl-regexp",
    "crates/bsl-format",
    "crates/bsl-bytecode",
    "crates/bsl-vm",
    "crates/bsl-cli",
    "crates/open-bsl",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"

[profile.profiling]
inherits = "release"
debug = true
