// Клиентский поиск по ранее подготовленным деревьям; только чтение.
Асинх Функция ПробаПоискаСсылок(ИдСсылок, ПутьСсылок, МаскаСсылок, РекурсияСсылок, КореньСсылок, ИмяПоиска)
	СтадияСсылок = "call";
	Попытка
		ОбещаниеСсылок = Вычислить(ИмяПоиска + "(ПутьСсылок, МаскаСсылок, РекурсияСсылок)");
		ПризнакОбещанияСсылок = ТипЗнч(ОбещаниеСсылок) = Тип("Обещание");
		СтадияСсылок = "await";
		НайденныеСсылки = Ждать ОбещаниеСсылок;
		ТекстСсылок = "promise=" + ?(ПризнакОбещанияСсылок, "1", "0") + "|ok|count=" + Строка(НайденныеСсылки.Количество());
		Для Каждого ЭлементСсылок Из НайденныеСсылки Цикл
			ТекстСсылок = ТекстСсылок + "|" + СтрЗаменить(ЭлементСсылок.ПолноеИмя, КореньСсылок, "<root>");
		КонецЦикла;
		Сообщить(ИдСсылок + Символ(9) + ТекстСсылок);
	Исключение
		Сообщить(ИдСсылок + Символ(9) + "error|stage=" + СтадияСсылок + "|" + ИнформацияОбОшибке().Описание);
	КонецПопытки;
	Возврат Неопределено;
КонецФункции

Асинх Процедура ИзмеритьПоискСсылокАсинх()
	Сообщить("file.begin" + Символ(9) + "file-search-links-async-1");
	КореньСсылок = "/tmp/open-bsl-find-link-controls-NhS1hY/tree";
	Ждать ПробаПоискаСсылок("async.ru.controls.plain.flat", КореньСсылок + "/plain", "*", Ложь, КореньСсылок, "НайтиФайлыАсинх");
	Ждать ПробаПоискаСсылок("async.ru.controls.plain.recursive", КореньСсылок + "/plain", "*", Истина, КореньСсылок, "НайтиФайлыАсинх");
	Ждать ПробаПоискаСсылок("async.ru.controls.plain.flat.txt", КореньСсылок + "/plain", "*.txt", Ложь, КореньСсылок, "НайтиФайлыАсинх");
	Ждать ПробаПоискаСсылок("async.ru.controls.plain.recursive.txt", КореньСсылок + "/plain", "*.txt", Истина, КореньСсылок, "НайтиФайлыАсинх");
	Ждать ПробаПоискаСсылок("async.ru.controls.file.flat", КореньСсылок + "/file", "*", Ложь, КореньСсылок, "НайтиФайлыАсинх");
	Ждать ПробаПоискаСсылок("async.ru.controls.file.recursive", КореньСсылок + "/file", "*", Истина, КореньСсылок, "НайтиФайлыАсинх");
	Ждать ПробаПоискаСсылок("async.ru.controls.file.flat.txt", КореньСсылок + "/file", "*.txt", Ложь, КореньСсылок, "НайтиФайлыАсинх");
	Ждать ПробаПоискаСсылок("async.ru.controls.file.recursive.txt", КореньСсылок + "/file", "*.txt", Истина, КореньСсылок, "НайтиФайлыАсинх");
	Ждать ПробаПоискаСсылок("async.ru.controls.dir.flat", КореньСсылок + "/dir", "*", Ложь, КореньСсылок, "НайтиФайлыАсинх");
	Ждать ПробаПоискаСсылок("async.ru.controls.dir.recursive", КореньСсылок + "/dir", "*", Истина, КореньСсылок, "НайтиФайлыАсинх");
	Ждать ПробаПоискаСсылок("async.ru.controls.dir.flat.txt", КореньСсылок + "/dir", "*.txt", Ложь, КореньСсылок, "НайтиФайлыАсинх");
	Ждать ПробаПоискаСсылок("async.ru.controls.dir.recursive.txt", КореньСсылок + "/dir", "*.txt", Истина, КореньСсылок, "НайтиФайлыАсинх");
	Ждать ПробаПоискаСсылок("async.ru.controls.broken.flat", КореньСсылок + "/broken", "*", Ложь, КореньСсылок, "НайтиФайлыАсинх");
	Ждать ПробаПоискаСсылок("async.ru.controls.broken.recursive", КореньСсылок + "/broken", "*", Истина, КореньСсылок, "НайтиФайлыАсинх");
	Ждать ПробаПоискаСсылок("async.ru.controls.broken.flat.txt", КореньСсылок + "/broken", "*.txt", Ложь, КореньСсылок, "НайтиФайлыАсинх");
	Ждать ПробаПоискаСсылок("async.ru.controls.broken.recursive.txt", КореньСсылок + "/broken", "*.txt", Истина, КореньСсылок, "НайтиФайлыАсинх");
	Ждать ПробаПоискаСсылок("async.ru.controls.valid.flat", КореньСсылок + "/valid", "*", Ложь, КореньСсылок, "НайтиФайлыАсинх");
	Ждать ПробаПоискаСсылок("async.ru.controls.valid.recursive", КореньСсылок + "/valid", "*", Истина, КореньСсылок, "НайтиФайлыАсинх");
	Ждать ПробаПоискаСсылок("async.ru.controls.valid.flat.txt", КореньСсылок + "/valid", "*.txt", Ложь, КореньСсылок, "НайтиФайлыАсинх");
	Ждать ПробаПоискаСсылок("async.ru.controls.valid.recursive.txt", КореньСсылок + "/valid", "*.txt", Истина, КореньСсылок, "НайтиФайлыАсинх");
	Ждать ПробаПоискаСсылок("async.ru.controls.mixed.flat", КореньСсылок + "/mixed", "*", Ложь, КореньСсылок, "НайтиФайлыАсинх");
	Ждать ПробаПоискаСсылок("async.ru.controls.mixed.recursive", КореньСсылок + "/mixed", "*", Истина, КореньСсылок, "НайтиФайлыАсинх");
	Ждать ПробаПоискаСсылок("async.ru.controls.mixed.flat.txt", КореньСсылок + "/mixed", "*.txt", Ложь, КореньСсылок, "НайтиФайлыАсинх");
	Ждать ПробаПоискаСсылок("async.ru.controls.mixed.recursive.txt", КореньСсылок + "/mixed", "*.txt", Истина, КореньСсылок, "НайтиФайлыАсинх");
	КореньСсылок = "/tmp/open-bsl-find-link-controls-NhS1hY/tree";
	Ждать ПробаПоискаСсылок("async.en.controls.plain.flat", КореньСсылок + "/plain", "*", Ложь, КореньСсылок, "FindFilesAsync");
	Ждать ПробаПоискаСсылок("async.en.controls.plain.recursive", КореньСсылок + "/plain", "*", Истина, КореньСсылок, "FindFilesAsync");
	Ждать ПробаПоискаСсылок("async.en.controls.plain.flat.txt", КореньСсылок + "/plain", "*.txt", Ложь, КореньСсылок, "FindFilesAsync");
	Ждать ПробаПоискаСсылок("async.en.controls.plain.recursive.txt", КореньСсылок + "/plain", "*.txt", Истина, КореньСсылок, "FindFilesAsync");
	Ждать ПробаПоискаСсылок("async.en.controls.file.flat", КореньСсылок + "/file", "*", Ложь, КореньСсылок, "FindFilesAsync");
	Ждать ПробаПоискаСсылок("async.en.controls.file.recursive", КореньСсылок + "/file", "*", Истина, КореньСсылок, "FindFilesAsync");
	Ждать ПробаПоискаСсылок("async.en.controls.file.flat.txt", КореньСсылок + "/file", "*.txt", Ложь, КореньСсылок, "FindFilesAsync");
	Ждать ПробаПоискаСсылок("async.en.controls.file.recursive.txt", КореньСсылок + "/file", "*.txt", Истина, КореньСсылок, "FindFilesAsync");
	Ждать ПробаПоискаСсылок("async.en.controls.dir.flat", КореньСсылок + "/dir", "*", Ложь, КореньСсылок, "FindFilesAsync");
	Ждать ПробаПоискаСсылок("async.en.controls.dir.recursive", КореньСсылок + "/dir", "*", Истина, КореньСсылок, "FindFilesAsync");
	Ждать ПробаПоискаСсылок("async.en.controls.dir.flat.txt", КореньСсылок + "/dir", "*.txt", Ложь, КореньСсылок, "FindFilesAsync");
	Ждать ПробаПоискаСсылок("async.en.controls.dir.recursive.txt", КореньСсылок + "/dir", "*.txt", Истина, КореньСсылок, "FindFilesAsync");
	Ждать ПробаПоискаСсылок("async.en.controls.broken.flat", КореньСсылок + "/broken", "*", Ложь, КореньСсылок, "FindFilesAsync");
	Ждать ПробаПоискаСсылок("async.en.controls.broken.recursive", КореньСсылок + "/broken", "*", Истина, КореньСсылок, "FindFilesAsync");
	Ждать ПробаПоискаСсылок("async.en.controls.broken.flat.txt", КореньСсылок + "/broken", "*.txt", Ложь, КореньСсылок, "FindFilesAsync");
	Ждать ПробаПоискаСсылок("async.en.controls.broken.recursive.txt", КореньСсылок + "/broken", "*.txt", Истина, КореньСсылок, "FindFilesAsync");
	Ждать ПробаПоискаСсылок("async.en.controls.valid.flat", КореньСсылок + "/valid", "*", Ложь, КореньСсылок, "FindFilesAsync");
	Ждать ПробаПоискаСсылок("async.en.controls.valid.recursive", КореньСсылок + "/valid", "*", Истина, КореньСсылок, "FindFilesAsync");
	Ждать ПробаПоискаСсылок("async.en.controls.valid.flat.txt", КореньСсылок + "/valid", "*.txt", Ложь, КореньСсылок, "FindFilesAsync");
	Ждать ПробаПоискаСсылок("async.en.controls.valid.recursive.txt", КореньСсылок + "/valid", "*.txt", Истина, КореньСсылок, "FindFilesAsync");
	Ждать ПробаПоискаСсылок("async.en.controls.mixed.flat", КореньСсылок + "/mixed", "*", Ложь, КореньСсылок, "FindFilesAsync");
	Ждать ПробаПоискаСсылок("async.en.controls.mixed.recursive", КореньСсылок + "/mixed", "*", Истина, КореньСсылок, "FindFilesAsync");
	Ждать ПробаПоискаСсылок("async.en.controls.mixed.flat.txt", КореньСсылок + "/mixed", "*.txt", Ложь, КореньСсылок, "FindFilesAsync");
	Ждать ПробаПоискаСсылок("async.en.controls.mixed.recursive.txt", КореньСсылок + "/mixed", "*.txt", Истина, КореньСсылок, "FindFilesAsync");
	КореньСсылок = "/tmp/open-bsl-find-broken-middle-0lH2uH/tree";
	Ждать ПробаПоискаСсылок("async.ru.middle.match.star.flat", КореньСсылок + "/match", "*", Ложь, КореньСсылок, "НайтиФайлыАсинх");
	Ждать ПробаПоискаСсылок("async.ru.middle.match.star.recursive", КореньСсылок + "/match", "*", Истина, КореньСсылок, "НайтиФайлыАсинх");
	Ждать ПробаПоискаСсылок("async.ru.middle.match.star_dot.flat", КореньСсылок + "/match", "*.*", Ложь, КореньСсылок, "НайтиФайлыАсинх");
	Ждать ПробаПоискаСсылок("async.ru.middle.match.star_dot.recursive", КореньСсылок + "/match", "*.*", Истина, КореньСсылок, "НайтиФайлыАсинх");
	Ждать ПробаПоискаСсылок("async.ru.middle.match.txt.flat", КореньСсылок + "/match", "*.txt", Ложь, КореньСсылок, "НайтиФайлыАсинх");
	Ждать ПробаПоискаСсылок("async.ru.middle.match.txt.recursive", КореньСсылок + "/match", "*.txt", Истина, КореньСсылок, "НайтиФайлыАсинх");
	Ждать ПробаПоискаСсылок("async.ru.middle.match.bin.flat", КореньСсылок + "/match", "*.bin", Ложь, КореньСсылок, "НайтиФайлыАсинх");
	Ждать ПробаПоискаСсылок("async.ru.middle.match.bin.recursive", КореньСсылок + "/match", "*.bin", Истина, КореньСсылок, "НайтиФайлыАсинх");
	Ждать ПробаПоискаСсылок("async.ru.middle.match.prefix_b.flat", КореньСсылок + "/match", "b*", Ложь, КореньСсылок, "НайтиФайлыАсинх");
	Ждать ПробаПоискаСсылок("async.ru.middle.match.prefix_b.recursive", КореньСсылок + "/match", "b*", Истина, КореньСсылок, "НайтиФайлыАсинх");
	Ждать ПробаПоискаСсылок("async.ru.middle.match.prefix_a.flat", КореньСсылок + "/match", "a*", Ложь, КореньСсылок, "НайтиФайлыАсинх");
	Ждать ПробаПоискаСсылок("async.ru.middle.match.prefix_a.recursive", КореньСсылок + "/match", "a*", Истина, КореньСсылок, "НайтиФайлыАсинх");
	Ждать ПробаПоискаСсылок("async.ru.middle.match.exact.flat", КореньСсылок + "/match", "broken.txt", Ложь, КореньСсылок, "НайтиФайлыАсинх");
	Ждать ПробаПоискаСсылок("async.ru.middle.match.exact.recursive", КореньСсылок + "/match", "broken.txt", Истина, КореньСсылок, "НайтиФайлыАсинх");
	Ждать ПробаПоискаСсылок("async.ru.middle.skip.star.flat", КореньСсылок + "/skip", "*", Ложь, КореньСсылок, "НайтиФайлыАсинх");
	Ждать ПробаПоискаСсылок("async.ru.middle.skip.star.recursive", КореньСсылок + "/skip", "*", Истина, КореньСсылок, "НайтиФайлыАсинх");
	Ждать ПробаПоискаСсылок("async.ru.middle.skip.star_dot.flat", КореньСсылок + "/skip", "*.*", Ложь, КореньСсылок, "НайтиФайлыАсинх");
	Ждать ПробаПоискаСсылок("async.ru.middle.skip.star_dot.recursive", КореньСсылок + "/skip", "*.*", Истина, КореньСсылок, "НайтиФайлыАсинх");
	Ждать ПробаПоискаСсылок("async.ru.middle.skip.txt.flat", КореньСсылок + "/skip", "*.txt", Ложь, КореньСсылок, "НайтиФайлыАсинх");
	Ждать ПробаПоискаСсылок("async.ru.middle.skip.txt.recursive", КореньСсылок + "/skip", "*.txt", Истина, КореньСсылок, "НайтиФайлыАсинх");
	Ждать ПробаПоискаСсылок("async.ru.middle.skip.bin.flat", КореньСсылок + "/skip", "*.bin", Ложь, КореньСсылок, "НайтиФайлыАсинх");
	Ждать ПробаПоискаСсылок("async.ru.middle.skip.bin.recursive", КореньСсылок + "/skip", "*.bin", Истина, КореньСсылок, "НайтиФайлыАсинх");
	Ждать ПробаПоискаСсылок("async.ru.middle.skip.prefix_b.flat", КореньСсылок + "/skip", "b*", Ложь, КореньСсылок, "НайтиФайлыАсинх");
	Ждать ПробаПоискаСсылок("async.ru.middle.skip.prefix_b.recursive", КореньСсылок + "/skip", "b*", Истина, КореньСсылок, "НайтиФайлыАсинх");
	Ждать ПробаПоискаСсылок("async.ru.middle.skip.prefix_a.flat", КореньСсылок + "/skip", "a*", Ложь, КореньСсылок, "НайтиФайлыАсинх");
	Ждать ПробаПоискаСсылок("async.ru.middle.skip.prefix_a.recursive", КореньСсылок + "/skip", "a*", Истина, КореньСсылок, "НайтиФайлыАсинх");
	Ждать ПробаПоискаСсылок("async.ru.middle.skip.exact.flat", КореньСсылок + "/skip", "broken.txt", Ложь, КореньСсылок, "НайтиФайлыАсинх");
	Ждать ПробаПоискаСсылок("async.ru.middle.skip.exact.recursive", КореньСсылок + "/skip", "broken.txt", Истина, КореньСсылок, "НайтиФайлыАсинх");
	Ждать ПробаПоискаСсылок("async.ru.middle.dir.star.flat", КореньСсылок + "/dir", "*", Ложь, КореньСсылок, "НайтиФайлыАсинх");
	Ждать ПробаПоискаСсылок("async.ru.middle.dir.star.recursive", КореньСсылок + "/dir", "*", Истина, КореньСсылок, "НайтиФайлыАсинх");
	Ждать ПробаПоискаСсылок("async.ru.middle.dir.star_dot.flat", КореньСсылок + "/dir", "*.*", Ложь, КореньСсылок, "НайтиФайлыАсинх");
	Ждать ПробаПоискаСсылок("async.ru.middle.dir.star_dot.recursive", КореньСсылок + "/dir", "*.*", Истина, КореньСсылок, "НайтиФайлыАсинх");
	Ждать ПробаПоискаСсылок("async.ru.middle.dir.txt.flat", КореньСсылок + "/dir", "*.txt", Ложь, КореньСсылок, "НайтиФайлыАсинх");
	Ждать ПробаПоискаСсылок("async.ru.middle.dir.txt.recursive", КореньСсылок + "/dir", "*.txt", Истина, КореньСсылок, "НайтиФайлыАсинх");
	Ждать ПробаПоискаСсылок("async.ru.middle.dir.bin.flat", КореньСсылок + "/dir", "*.bin", Ложь, КореньСсылок, "НайтиФайлыАсинх");
	Ждать ПробаПоискаСсылок("async.ru.middle.dir.bin.recursive", КореньСсылок + "/dir", "*.bin", Истина, КореньСсылок, "НайтиФайлыАсинх");
	Ждать ПробаПоискаСсылок("async.ru.middle.dir.prefix_b.flat", КореньСсылок + "/dir", "b*", Ложь, КореньСсылок, "НайтиФайлыАсинх");
	Ждать ПробаПоискаСсылок("async.ru.middle.dir.prefix_b.recursive", КореньСсылок + "/dir", "b*", Истина, КореньСсылок, "НайтиФайлыАсинх");
	Ждать ПробаПоискаСсылок("async.ru.middle.dir.prefix_a.flat", КореньСсылок + "/dir", "a*", Ложь, КореньСсылок, "НайтиФайлыАсинх");
	Ждать ПробаПоискаСсылок("async.ru.middle.dir.prefix_a.recursive", КореньСсылок + "/dir", "a*", Истина, КореньСсылок, "НайтиФайлыАсинх");
	Ждать ПробаПоискаСсылок("async.ru.middle.dir.exact.flat", КореньСсылок + "/dir", "broken.txt", Ложь, КореньСсылок, "НайтиФайлыАсинх");
	Ждать ПробаПоискаСсылок("async.ru.middle.dir.exact.recursive", КореньСсылок + "/dir", "broken.txt", Истина, КореньСсылок, "НайтиФайлыАсинх");
	КореньСсылок = "/tmp/open-bsl-find-broken-middle-0lH2uH/tree";
	Ждать ПробаПоискаСсылок("async.en.middle.match.star.flat", КореньСсылок + "/match", "*", Ложь, КореньСсылок, "FindFilesAsync");
	Ждать ПробаПоискаСсылок("async.en.middle.match.star.recursive", КореньСсылок + "/match", "*", Истина, КореньСсылок, "FindFilesAsync");
	Ждать ПробаПоискаСсылок("async.en.middle.match.star_dot.flat", КореньСсылок + "/match", "*.*", Ложь, КореньСсылок, "FindFilesAsync");
	Ждать ПробаПоискаСсылок("async.en.middle.match.star_dot.recursive", КореньСсылок + "/match", "*.*", Истина, КореньСсылок, "FindFilesAsync");
	Ждать ПробаПоискаСсылок("async.en.middle.match.txt.flat", КореньСсылок + "/match", "*.txt", Ложь, КореньСсылок, "FindFilesAsync");
	Ждать ПробаПоискаСсылок("async.en.middle.match.txt.recursive", КореньСсылок + "/match", "*.txt", Истина, КореньСсылок, "FindFilesAsync");
	Ждать ПробаПоискаСсылок("async.en.middle.match.bin.flat", КореньСсылок + "/match", "*.bin", Ложь, КореньСсылок, "FindFilesAsync");
	Ждать ПробаПоискаСсылок("async.en.middle.match.bin.recursive", КореньСсылок + "/match", "*.bin", Истина, КореньСсылок, "FindFilesAsync");
	Ждать ПробаПоискаСсылок("async.en.middle.match.prefix_b.flat", КореньСсылок + "/match", "b*", Ложь, КореньСсылок, "FindFilesAsync");
	Ждать ПробаПоискаСсылок("async.en.middle.match.prefix_b.recursive", КореньСсылок + "/match", "b*", Истина, КореньСсылок, "FindFilesAsync");
	Ждать ПробаПоискаСсылок("async.en.middle.match.prefix_a.flat", КореньСсылок + "/match", "a*", Ложь, КореньСсылок, "FindFilesAsync");
	Ждать ПробаПоискаСсылок("async.en.middle.match.prefix_a.recursive", КореньСсылок + "/match", "a*", Истина, КореньСсылок, "FindFilesAsync");
	Ждать ПробаПоискаСсылок("async.en.middle.match.exact.flat", КореньСсылок + "/match", "broken.txt", Ложь, КореньСсылок, "FindFilesAsync");
	Ждать ПробаПоискаСсылок("async.en.middle.match.exact.recursive", КореньСсылок + "/match", "broken.txt", Истина, КореньСсылок, "FindFilesAsync");
	Ждать ПробаПоискаСсылок("async.en.middle.skip.star.flat", КореньСсылок + "/skip", "*", Ложь, КореньСсылок, "FindFilesAsync");
	Ждать ПробаПоискаСсылок("async.en.middle.skip.star.recursive", КореньСсылок + "/skip", "*", Истина, КореньСсылок, "FindFilesAsync");
	Ждать ПробаПоискаСсылок("async.en.middle.skip.star_dot.flat", КореньСсылок + "/skip", "*.*", Ложь, КореньСсылок, "FindFilesAsync");
	Ждать ПробаПоискаСсылок("async.en.middle.skip.star_dot.recursive", КореньСсылок + "/skip", "*.*", Истина, КореньСсылок, "FindFilesAsync");
	Ждать ПробаПоискаСсылок("async.en.middle.skip.txt.flat", КореньСсылок + "/skip", "*.txt", Ложь, КореньСсылок, "FindFilesAsync");
	Ждать ПробаПоискаСсылок("async.en.middle.skip.txt.recursive", КореньСсылок + "/skip", "*.txt", Истина, КореньСсылок, "FindFilesAsync");
	Ждать ПробаПоискаСсылок("async.en.middle.skip.bin.flat", КореньСсылок + "/skip", "*.bin", Ложь, КореньСсылок, "FindFilesAsync");
	Ждать ПробаПоискаСсылок("async.en.middle.skip.bin.recursive", КореньСсылок + "/skip", "*.bin", Истина, КореньСсылок, "FindFilesAsync");
	Ждать ПробаПоискаСсылок("async.en.middle.skip.prefix_b.flat", КореньСсылок + "/skip", "b*", Ложь, КореньСсылок, "FindFilesAsync");
	Ждать ПробаПоискаСсылок("async.en.middle.skip.prefix_b.recursive", КореньСсылок + "/skip", "b*", Истина, КореньСсылок, "FindFilesAsync");
	Ждать ПробаПоискаСсылок("async.en.middle.skip.prefix_a.flat", КореньСсылок + "/skip", "a*", Ложь, КореньСсылок, "FindFilesAsync");
	Ждать ПробаПоискаСсылок("async.en.middle.skip.prefix_a.recursive", КореньСсылок + "/skip", "a*", Истина, КореньСсылок, "FindFilesAsync");
	Ждать ПробаПоискаСсылок("async.en.middle.skip.exact.flat", КореньСсылок + "/skip", "broken.txt", Ложь, КореньСсылок, "FindFilesAsync");
	Ждать ПробаПоискаСсылок("async.en.middle.skip.exact.recursive", КореньСсылок + "/skip", "broken.txt", Истина, КореньСсылок, "FindFilesAsync");
	Ждать ПробаПоискаСсылок("async.en.middle.dir.star.flat", КореньСсылок + "/dir", "*", Ложь, КореньСсылок, "FindFilesAsync");
	Ждать ПробаПоискаСсылок("async.en.middle.dir.star.recursive", КореньСсылок + "/dir", "*", Истина, КореньСсылок, "FindFilesAsync");
	Ждать ПробаПоискаСсылок("async.en.middle.dir.star_dot.flat", КореньСсылок + "/dir", "*.*", Ложь, КореньСсылок, "FindFilesAsync");
	Ждать ПробаПоискаСсылок("async.en.middle.dir.star_dot.recursive", КореньСсылок + "/dir", "*.*", Истина, КореньСсылок, "FindFilesAsync");
	Ждать ПробаПоискаСсылок("async.en.middle.dir.txt.flat", КореньСсылок + "/dir", "*.txt", Ложь, КореньСсылок, "FindFilesAsync");
	Ждать ПробаПоискаСсылок("async.en.middle.dir.txt.recursive", КореньСсылок + "/dir", "*.txt", Истина, КореньСсылок, "FindFilesAsync");
	Ждать ПробаПоискаСсылок("async.en.middle.dir.bin.flat", КореньСсылок + "/dir", "*.bin", Ложь, КореньСсылок, "FindFilesAsync");
	Ждать ПробаПоискаСсылок("async.en.middle.dir.bin.recursive", КореньСсылок + "/dir", "*.bin", Истина, КореньСсылок, "FindFilesAsync");
	Ждать ПробаПоискаСсылок("async.en.middle.dir.prefix_b.flat", КореньСсылок + "/dir", "b*", Ложь, КореньСсылок, "FindFilesAsync");
	Ждать ПробаПоискаСсылок("async.en.middle.dir.prefix_b.recursive", КореньСсылок + "/dir", "b*", Истина, КореньСсылок, "FindFilesAsync");
	Ждать ПробаПоискаСсылок("async.en.middle.dir.prefix_a.flat", КореньСсылок + "/dir", "a*", Ложь, КореньСсылок, "FindFilesAsync");
	Ждать ПробаПоискаСсылок("async.en.middle.dir.prefix_a.recursive", КореньСсылок + "/dir", "a*", Истина, КореньСсылок, "FindFilesAsync");
	Ждать ПробаПоискаСсылок("async.en.middle.dir.exact.flat", КореньСсылок + "/dir", "broken.txt", Ложь, КореньСсылок, "FindFilesAsync");
	Ждать ПробаПоискаСсылок("async.en.middle.dir.exact.recursive", КореньСсылок + "/dir", "broken.txt", Истина, КореньСсылок, "FindFilesAsync");
	Сообщить("file.end" + Символ(9) + "file-search-links-async-1");
	Попытка
		Выполнить("ЗавершитьРаботуСистемы(Ложь)");
	Исключение
	КонецПопытки;
КонецПроцедуры

ИзмеритьПоискСсылокАсинх();
