[package]
name = "open-bsl"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
default = ["regexp"]
binbuf = []
stream = []
json = []
xml = []
pdf = []
zip = []
spreadsheet = []
textdoc = []
regexp = ["dep:bsl-regexp", "bsl-vm/regexp"]

[dependencies]
bsl-bytecode = { path = "../bsl-bytecode" }
bsl-rt = { path = "../bsl-rt" }
bsl-sema = { path = "../bsl-sema" }
bsl-syntax = { path = "../bsl-syntax" }
bsl-vm = { path = "../bsl-vm", default-features = false }
bsl-regexp = { path = "../bsl-regexp", optional = true }
